### PR TITLE
feat(search): match DocSearch style with Neovim

### PR DESCRIPTION
**Pull request by shortcuts**
> disclaimer: take a look at https://github.com/neovim/neovim.github.io/pull/328 first as this branch is stacked on it.

This PR aims at matching the DocSearch styles to the Neovim colors, see table for preview.

| Description | Before | After |
|:--------:|--------|--------|
| Update of the search button and keys | Screenshot 2023-06-28 at 00 11 16 | Screenshot 2023-06-28 at 22 45 57 |
| Update of the modal and result highlights | Screenshot 2023-06-28 at 00 12 01 | Screenshot 2023-06-28 at 00 12 21 | 

Feel free to suggest changes / color variations.

### CODE REVIEW

**Comment by justinmk** [comment]
Beautiful. Only nit is that the top-right search box is now rather subdued, I think it's useful for it to be kind of obvious. Could its border be radioactive green like the popup input:

image

**Comment by teto** [comment]
I was going to do the same comment, the search bar is too subtle.The new modal is top notch

**Comment by shortcuts** [comment]
Thanks for the feedback and glad you like it! Will make the changes by the end of the day

**Comment by shortcuts** [comment]
@justinmk @teto updated the style and PR body to have a green border on the search button

**Comment by teto** [comment]
It's better. Fine by me. You might want to rebase to resolve the merge conflict.

**Pull request merged**
