### PR TITLE
Install Now button on homepage

### PR DESCRIPTION
**Pull request by brycefisher**
See https://github.com/neovim/neovim.github.io/issues/134

homepage-install-button

### CODE REVIEW

**Comment by justinmk** [comment]
Heh, seems fine to me. Any way to make the font a bit bigger, and the button may a bit smaller (perhaps more narrow than the text above it, at least)? It seems kind of insanely big :)

**Comment by brycefisher** [comment]
Yes! This was a quick and dirty first pass, but totally agree. I'll try to get that change back to you tonight (PST)

**Comment by brycefisher** [comment]
Also, looks like the Gemfile is out of date? Known issue?

**Comment by justinmk** [comment]
You mean Gemfile.lock? Not sure.

See https://github.com/github/pages-gem for explanation of the Gemfile itself.

**Comment by brycefisher** [comment]
I'm not really sure. I was just looking at why the Travis build failed and I saw this error:

> $ bundle exec rake
> /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:256:in \`block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
>	from /home/travis/.rvm/gems/ruby-2.2.0/bin/rake:22:in \`\<main>'
>	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in \`eval'
>	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in \`\<main>'
> The command "bundle exec rake" exited with 1.

**Comment by justinmk** [comment]
Ok, maybe adding `gem 'rake'` to Gemfile will fix it.

**Comment by brycefisher** [comment]
Awesome! Will try that tonight.

**Comment by brycefisher** [comment]
Visual changes:

better-button

Also, finally got jekyll working for me locally in a custom docker image. Fingers crossed my changes also make Travis happy  :sweat_smile:

**Comment by justinmk** [comment]
Looks great. I have no idea what Travis is even testing on this repo. Except I guess the basic gem install.

**Comment by brycefisher** [comment]
Its actually checking for deadlinks and a few things that html-proofer provides (first time I've heard of that gem, but super super awesome tool).

**Comment by brycefisher** [comment]
Well, I'm running out of time for tonight. @justinmk let me know if I should:

 1. keep banging on travis/html-proofer
 2. pull that into a separate PR (since its completely orthogonal to the cosmetic changes which inspired this PR), or
 3. just remove html-proofer for now as part of this PR.

**Comment by justinmk** [comment]
Thanks for cleaning this up. I'll wait for the buld result, I think you figured it out.

**Comment by brycefisher** [comment]
@justinmk I'm getting closer, but still no :smoking:

**Comment by brycefisher** [comment]
Arg, I'm making progress locally but travis is behaving a bit differently. I'm done for tonight but let me know how you want to proceed here @justinmk

**Comment by justinmk** [comment]
Thanks, no rush. We can push the button tomorrow and continue fixing travis in another PR if you can.

**Comment by brycefisher** [comment]
Sounds good!

**Comment by brycefisher** [comment]
Closing this PR, but keeping the branch on my fork to create a new PR that gets html-proofer up and running as a Rake task

**Comment by justinmk** [comment]
@brycefisher Do you think you will be able to get the html-proofer running?

**Pull request closed without merging**
