### PR TITLE
Refer to newsletter as 'bimonthly' instead of 'monthly'.

### PR DESCRIPTION
**Pull request by tpz**
The release interval for the newsletters was changed a few months ago.

### CODE REVIEW

**Comment by jdavis** [comment]
Considering bi-monthly is ambiguous, would "every other month" be better?

**Comment by justinmk** [comment]
maybe quasi-monthly :)

**Comment by jdavis** [comment]
I think either would work. @tpz Would you be alright changing it to one of these?

**Comment by jdavis** [comment]
I'm closing this since @tpz hasn't returned to address the suggestions.

**Pull request closed without merging**
