### PR TITLE
Website updates

### PR DESCRIPTION
**Pull request by tjdevries**
Add an auto-updating post field.

Very open to suggestions for styling or different word choices.

Looks like this

### CODE REVIEW

**Comment by justinmk** [comment]
Nice! It probably should go "above the fold", perhaps in a "News" section or whatever. Let's limit it to the last 2 newsletters so that it doesn't take too much room.

**Comment by tjdevries** [comment]
screenshot 2016-09-27 at 8 56 11 pm

New section and only two posts

**Comment by toogley** [comment]
@justinmk what's the current status of this PR? it seems @tjdevries has addressed your concerns.

**Comment by justinmk** [comment]
Let's try it out. Thanks @tjdevries !

**Pull request merged**
