### PR TITLE
Refine Light/Dark colors

### PR DESCRIPTION
**Pull request by rockerBOO**
Continuing https://github.com/neovim/neovim.github.io/pull/203

This refines the current colors from more primary colors and shifts everything into the blue/green hue.

All colors to be AAA contrast accessibility. Except for the blue links on the dark background are AA. Blue is darker generally and this allowed us to keep the blue color more. 

Added underlines to all links. This helps with accessibility and scanning to find the links easily. 

Unset a lot of bootstrap values to set the font size in `<pre>`. Now defaults to the user's `monospace` font and their default browser font size for monospace. This allows users to use the font they like as well as support ligatures ;).

Changed the main button to be `Get Started` from `Install Now`. Add animated effect on hover/focus.

Adds animation (96ms) to link transitions.

Screenshot_2020-12-17 Home - Neovim(4)
Screenshot_2020-12-17 Home - Neovim(3)

### CODE REVIEW

**Comment by jamessan** [comment]
Thanks for the work on this and your patience!  Merging.

**Comment by justinmk** [comment]
> Changed the main button to be `Get Started` from `Install Now`.

I reverted this wording change, because "Get Started" sounds too vague and cumbersome (analogous to "call for a quote!" instead of just saying what the price is).

**Comment by rockerBOO** [comment]
I was using "Get Started" instead of "Install Now" because clicking the button doesn't install anything. Alternatively used is "Download X" or just "Download". To me it felt misleading. Also using "now" adds a level to anxiety to it, to do it now vs just showing them the path. Just my opinion though.

https://www.rust-lang.org/
https://golang.org/
https://code.visualstudio.com/
https://www.sublimetext.com/
https://www.jetbrains.com/idea/

**Comment by justinmk** [comment]
good references. "Download" could work, but the "Install" page has many different install vectors, idk

**Comment by rockerBOO** [comment]
I was thinking some more and I think just "Install Neovim" would work well here.

**Comment by justinmk** [comment]
@rockerBOO Just want to say you did an awesome job on the light color scheme (too!). I'm usually in dark mode but the light scheme on neovim.io looks so good!

**Pull request merged**
