### PR TITLE
[RFC] Move original backers to sponsors page.

### PR DESCRIPTION
**Pull request by fwalch**
Maybe we should have an email address for sponsors to write to.. as it says on the page, not everybody has a GitHub account, so they can't send a pull request to update the sponsors-override file.

gui

### CODE REVIEW

**Comment by tarruda** [comment]
:+1: 

> Maybe we should have an email address for sponsors to write to.. as it says on the page, not everybody has a GitHub account, so they can't send a pull request to update the sponsors-override file.

True, we can use the mailing list for that. Can you add this information?

**Comment by fwalch** [comment]
Added: "If you don't have a GitHub account, you can write to the Neovim mailing list instead."

**Comment by fwalch** [comment]
@tarruda [uBlock](http://ublock.org/) doesn't seem to like (i.e. hides) elements that contain "logo" in their CSS class.. something like the following fixes that:

```diff
diff --git a/sponsor-generator/lib/sponsor.ejs b/sponsor-generator/lib/sponsor.ejs
index 45c8b48..bbb20fe 100644
--- a/sponsor-generator/lib/sponsor.ejs
+++ b/sponsor-generator/lib/sponsor.ejs
@@ -1,5 +1,5 @@
 <tr class="sponsor">
-<td class="sponsor-logo">
+<td class="sponsor-image">
   <% if (url) { %>
   <a href="<%= url %>"><img src="<%= logo %>"></img></a>
   <% } else { %>
diff --git a/sponsor-generator/lib/sponsor_front.ejs b/sponsor-generator/lib/sponsor_front.ejs
index ccfdc16..eb972f2 100644
--- a/sponsor-generator/lib/sponsor_front.ejs
+++ b/sponsor-generator/lib/sponsor_front.ejs
@@ -1,5 +1,5 @@
 <div class="sponsor-front">
-<div class="sponsor-logo">
+<div class="sponsor-image">
   <% if (url) { %>
   <a href="<%= url %>"><img src="<%= frontLogo %>" alt="Logo of <%= name %>"></img></a>
   <% } else { %>
```

I didn't add it as a commit here because I didn't know how to create the `.js` file from the `ejs`.

**Comment by tarruda** [comment]
> @tarruda uBlock doesn't seem to like (i.e. hides) elements that contain "logo" in their CSS class.. something like the following should fix that:

:+1:

> I didn't add it as a commit here because I didn't know how to create the .js file from the ejs.

After installing node.js/io.js(io.js seems more stable), install `gulp` which is the build tool I used to bundle javascript(only need sudo if you are using a system-wide installation of node.js):

```
sudo npm install -g gulp
```

Then from the `sponsor-generator` directory install the dependencies and recreate the bundle:

```
npm install
gulp
```

This will leave a modified javascript file in the `js` directory which you can commit.

**Comment by fwalch** [comment]
Thanks for the instructions, pushed a commit.

**Comment by tarruda** [comment]
Thanks

**Pull request merged**
