### PR TITLE
Added a link and a front-image for my slug

### PR DESCRIPTION
**Pull request by ganwell**
I was a bit surprised that I ended up on the front page of neovim.io. So I created a small page with few information about what I am working on.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks a lot!

**Comment by tarruda** [comment]
Thank you :smile:

**Comment by tarruda** [comment]
@ganwell there's now an issue because the front image URL comes from http and not https. Here's what chromium reports:

> Mixed Content: The page at 'https://neovim.io/' was loaded over HTTPS, but requested an insecure image 'http://1042.ch/ganwell.png'. This content should also be served over HTTPS.

and

> Image from origin 'http://1042.ch' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://neovim.io' is therefore not allowed access.

Any chance you can provide an https url for your front page image?

**Comment by ganwell** [comment]
@tarruda Thanks for fixing that. I totally forgot about the " Cross-Origin Resource Sharing" problem. And also thanks for the great software.

**Pull request merged**
