### PR TITLE
Use HTTPS where possible

### PR DESCRIPTION
**Pull request by charmander**
> This also fixes mixed-content warnings on https://neovim.org/ and adds a “www.” prefix when targets redirect to it.

### CODE REVIEW

**Comment by charmander** [comment]
Oops! This is very similar to #87, but that cleans up internal links better and doesn’t change all external links.

**Comment by cweagans** [comment]
I'd prefer to not do this. A successful PR, IMO, satisfies the following:

* All CSS/JS uses protocol relative URLs
* All internal links should be relative to the domain (`/doc/whatever` instead of `http://neovim.org/doc/whatever`)
* All external links should specify HTTPS for sites where it's available.

For an added bonus, it'd be awesome to automate these checks and include them in the Travis build.

**Comment by charmander** [comment]
> All CSS/JS uses protocol relative URLs

Why? (I’m just curious – using HTTPS even for `http:` pages doesn’t seem like a bad thing. Changes in this pull request were done for consistency with https://github.com/neovim/neovim.github.io/blob/1207875/_layouts/default.html#L25.)

Regarding the other two points, merging both of these pull requests should achieve the desired effect.

**Comment by cweagans** [comment]
Because local development environments typically don't have SSL set up. For external assets, I'm okay with just using https all the time, but for internal assets hosted on neovim.org, we need protocol relative URLs for sure.

**Comment by charmander** [comment]
Paths? Sure.

**Comment by justinmk** [comment]
AFAIK this was satisfied elsewhere.

**Pull request closed without merging**
