### PR TITLE
[RFC] Documentation page: Link to user resources on wiki.

### PR DESCRIPTION
**Pull request by fwalch**
There's a lot of questions coming up on the same topics: Python support, `:!` problems, CTRL-H problems. Link to the Troubleshooting page, where some of these issues are addressed (~~I plan to add something for CTRL-H~~ actually, since it's in the milestone for the first release, it should go away soon and doesn't need to be documented).

### CODE REVIEW

**Comment by Pyrohh** [comment]
Seems like a good idea.

**Comment by fwalch** [comment]
Added a link to the "breaking changes page" (neovim/neovim#2962).

**Comment by Pyrohh** [comment]
@fwalch would you mind taking a screenshot of the changes?. The instructions in README.md for previewing locally didn't work for me, and I can't find the instructions you posted for me a few months ago.

Sorry... :sweat:

**Comment by fwalch** [comment]
I'm not sure what I posted also, otherwise I would update the README right now... maybe figure it out later.

Screenshot:
gui

**Comment by Pyrohh** [comment]
LGTM

**Comment by justinmk** [comment]
Oh, the link checker failed on HTTP 429. I wonder if we can turn that off. For now, the build might fail in the meantime...

**Pull request merged**
