### PR TITLE
doc: restore uri neovim.io/doc

### PR DESCRIPTION
**Pull request by teto**
plus renamed doc2 to doc since it makes local editing easier.

### CODE REVIEW

**Comment by justinmk** [comment]
would rather revert the `doc/general/` thing and go back to having a single `doc/` landing page. The content of `doc/lsp/`, `doc/treesitter/`, etc. does not justify separate landing pages.

**Comment by justinmk** [comment]
> or we fix the generation of the website so https://neovim.io/doc/ works again.

yep, not sure where it went wrong, i guess the doc/index.html went missing

**Comment by justinmk** [comment]
> Especially as I think we may need to add more in the future (regarding all the recent talk about best practice for plugin development). Neovim doc is good but there is little on the website (a lot on the wiki) but hosting some on the website looks neater IMHO.

the website is not the primary source of truth. Detailed things should live mostly in the user manual and generate to the website.

There is no hard and fast rule that "multiple pages are discouraged", but it should solve a problem. The current tree is a solution looking for a problem.

Trying to fit the constraint of "all on one page" leads to useful questions like "do we actually need X or Y". Answer is "no" for some of the things under doc/ currently.

**Comment by justinmk** [comment]
`What is the Language Server Protocol ?` has no business being under doc/, for example. Yet that's all there is in the LSP page.

**Comment by teto** [comment]
> What is the Language Server Protocol ? has no business being under doc/, for example. 

I disagree, we've got tons of questions about what is LSP, what's the difference with treesitter, what is lspconfig, how it interacts with neovim and so on. It's a unique feature of neovim and if you have never used neovim, how are you supposed to know how to use LSP in neovim ? You have no nvim installed so `:h` is out of the question (plus it's tough for beginners). I think we need to mention lspconfig here. Is it worth having mutiple pages, maybe not. But I can imagine this going up a bit. We could add animations to showcase the feature. I would prefer it on a lsp page rather than https://neovim.io/screenshots/ .

**Comment by jamessan** [comment]
FWIW, I've restored the https://neovim.io/doc/ URL in #271.  I'll let you guys decide on how to handle the broader issue that Justin raised, but the 404 is now fixed.

**Pull request closed without merging**
