### PR TITLE
Move all assets to self-hosting

### PR DESCRIPTION
**Pull request by rockerBOO**
This removes all the various CDN hosting to utilize HTTP2 and not leak access data of our users. 

* Bootstrap (css/js)
* Normalize.css
* Google Font (Lato) moved inline (only supporting modern browsers, others will default nicely)
* Jquery

### CODE REVIEW

**Comment by teto** [comment]
I approve but I worry for maintenance: is there a webdev tool to update those or should we do it manually ? Its neither critical nor frequent but I thought I would ask nonetheless

**Comment by rockerBOO** [comment]
Bootstrap is the main requirement which does not need to be updated. JQuery was dropped in the future versions. Only reason we need JQuery now is to do the small dropdown thing on the "About" item in the navigation. 

Normalize is pretty common but is a separate thing.

In terms of updating, they are all listed in default.html. The source minified files all have their version number in them.

**Comment by rockerBOO** [comment]
Maybe we can add a `vendor/` folder to give better indications.

**Comment by teto** [comment]
Nevermind it's simple enough like this. Will try it later and if no objection merge

**Pull request merged**
