### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by whereswaldon**
Just fixing a few typos that I saw when I was reading through. Also, I didn't know what it meant by "Yoda conditions" at first. I figured it out and added an example for contrast so that other people unfamiliar with the term don't have to leave the document to understand what is meant.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. So I think we should allow Yoda conventions.

**Comment by whereswaldon** [comment]
Anyone know why this doesn't work in Travis? I'm unfamiliar. The commit that it has an issue with is adding a single space.

**Comment by justinmk** [comment]
CI is broken on this repo. Haven't had chance to look at it.

**Comment by brycefisher** [comment]
@justinmk Im addressing Travis in my PR https://github.com/neovim/neovim.github.io/pull/135

**Pull request merged**
