### PR TITLE
link to questions tagged neovim in the SE site

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks, but the questions there aren't a great selection, and Neovim is still Vim, so we want users to understand that ViSE in general is relevant.

**Comment by waldyrious** [comment]
@justinmk I see your point. In all fairness, the link that I provided is sorted by "newest" by default. If I may offer a compromise,  Maybe [sorting it by votes](https://vi.stackexchange.com/questions/tagged/neovim?sort=votes) would make you more comfortable linking to it?

**Comment by justinmk** [comment]
There's only 10 questions. Maybe when there's a 100...

**Comment by waldyrious** [comment]
Well, that list is in flux, and it will grow the more people are pointed towards the tag, so it's in our best interests to point people there. Besides, I don't think anyone expects the Neovim project to guarantee the quality of third-party neovim-related resources (and even if they did, the questions closed as off-topic are the top-voted for some reason, and have had answers accepted, so they clearly have value to the community). Finally, note that the entry about the vim SE in the current list (before this PR) already points people to the tag, but offers no link to it, which IMO just makes things inconvenient for users.

**Pull request closed without merging**
