### PR TITLE
Update Sponsors info on Home Page

### PR DESCRIPTION
**Pull request by rockerBOO**
Update sponsors section on homepage to include (and prioritize github sponsors). 

Screenshot_2020-12-08 Home - Neovim(7)

### CODE REVIEW

**Comment by teto** [comment]
awesome ! I was looking forward for someone to do it ! 
maybe we should add https://opencollective.com/neovim too @jamessan ?

**Comment by rockerBOO** [comment]
Added Open Collective link 
Screenshot_2020-12-08 Home - Neovim(8)

**Comment by teto** [comment]
sorry to nitpick but I believe we want Open Collective before Bountysource. Bountysource is kinda erratic so people should use it last. Other than that good for me thanks

**Comment by rockerBOO** [comment]
No worries, good info to know. I plan on giving the sponsors page a rework with the new github sponsors integration.

**Comment by rockerBOO** [comment]
Screenshot_2020-12-08 Home - Neovim(9)

**Comment by teto** [comment]
thanks

**Comment by jamessan** [comment]
Honestly, I'd probably drop Bountysource.  We really just want to pay out from there and not really take more donations.  They're too flaky.

**Comment by rockerBOO** [comment]
I'll get them on another pass when I clean up the Sponsors page.

**Pull request merged**
