### PR TITLE
[RDY] Update sponsors for the new campaign

### PR DESCRIPTION
**Pull request by tarruda**
Bountysource has a json api that presents sponsor information sorted by amount. The sponsor-generator javascript library will download data from that API and do some image processing before inserting into the page(mostly transform the image to grayscale to match the site theme, as @jasonlong did on the first campaign).

I've tried to make things as automatic as possible, but unfortunately bountysource does not provide all information required to fulfill the new campaign rewards, so I've added the sponsors-override.js file to complement the bountysource API.

I'd love some help styling the new html as my CSS skills really stink :smile:

### CODE REVIEW

**Comment by tarruda** [comment]
I've added a temporary version here: http://tarruda.github.io/neovim.github.io/

**Comment by justinmk** [comment]
The hautlook URL seems wrong (shows "lorem ipsum" text)

**Comment by jasonlong** [comment]
I can probably take a look here. Possibly this weekend, but early next week probably. If someone else beats me to it, that's :cool:.

**Comment by tarruda** [comment]
> I can probably take a look here. Possibly this weekend, but early next week probably. If someone else beats me to it, that's :cool:.

@jasonlong thanks, that would be much appreciated :smile: 

I've made a few extra changes and think it's almost ready for merging. My main problem right now is setting the widths of the sponsors/faq columns in the [sponsors section](http://tarruda.github.io/neovim.github.io/sponsors/). I've tried using the css classes `col-wide` on the sponsors div and `col-narrow` on the FAQ, but for some reason they doesn't seem to affect anything, the FAQ column is always wider the the sponsors column

**Comment by tarruda** [comment]
> The hautlook URL seems wrong (shows "lorem ipsum" text)

This is the URL they requested bountysource to be posted.

**Comment by tarruda** [comment]
Merging now as I'm very late in fulfilling the rewards for the new campaign.

@jasonlong any feedback/suggestions you'd like to give later will be very welcome

**Pull request merged**
