### PR TITLE
Switch to HTTPS

### PR DESCRIPTION
**Pull request by jdavis**
Updates that go along with #86. @cweagans and @fwalch should take a look...

Once this is merged, then I'll update the Page Rules within Cloudflare.

### CODE REVIEW

**Comment by jdavis** [comment]
Updated, @cweagans

**Comment by fwalch** [comment]
The internal links can't be resolved on Travis because they are stored in `neovim/doc`... something like this might fix it:

```diff
diff --git a/Rakefile b/Rakefile
index 814a7ca..afad24b 100644
--- a/Rakefile
+++ b/Rakefile
@@ -2,6 +2,7 @@ require 'html/proofer'
 
 task :test do
   sh 'bundle exec jekyll build --drafts'
+  sh 'git clone --depth 1 https://github.com/neovim/doc ./_site/doc'
   HTML::Proofer.new('./_site',
     :parallel => { :in_threads => 4 },
     :href_swap => {
```

**Comment by jdavis** [comment]
@fwalch By cloning neovim/docs it just added like 10 minutes to the time it took to do the proofing and ended up with 1519 failures.

I ended up just using a regex to ignore the `/doc/*` links. Besides accidentally linking to a broken doc page and not noticing, this should be fine for the time being.

**Comment by jdavis** [comment]
Actually, I just realized that `alt_ignore` can be a regex; I had assumed it was a boolean.

It looks like we can just ignore the images on the doc pages. But there are still these HTML proofer problems:

```
- ./_site/doc/dev/classes.html
  *  image search/close.png does not have an alt attribute
  *  image search/mag_sel.png does not have an alt attribute
  *  linking to internal hash #letter_B that does not exist
  *  linking to internal hash #letter_G that does not exist
  *  linking to internal hash #letter_I that does not exist
  *  linking to internal hash #letter_K that does not exist
  *  linking to internal hash #letter_L that does not exist
  *  linking to internal hash #letter_X that does not exist
  *  linking to internal hash #letter_O that does not exist
  *  linking to internal hash #letter_Q that does not exist
  *  linking to internal hash #letter_X that does not exist
  *  linking to internal hash #letter_B that does not exist
  *  linking to internal hash #letter_G that does not exist
  *  linking to internal hash #letter_I that does not exist
  *  linking to internal hash #letter_K that does not exist
  *  linking to internal hash #letter_L that does not exist
  *  linking to internal hash #letter_N that does not exist
  *  linking to internal hash #letter_O that does not exist
  *  linking to internal hash #letter_Q that does not exist
  *  linking to internal hash #letter_N that does not exist
```

**Comment by justinmk** [comment]
neovim.io redirects to https now.

**Pull request closed without merging**
