### PR TITLE
[RDY] Enable Travis/HTML::Proofer

### PR DESCRIPTION
**Pull request by fwalch**
Inspired by https://github.com/blog/1939-how-github-uses-github-to-document-github. Would require this repo to be enabled on Travis.

[HTML::Proofer](https://github.com/gjtorikian/html-proofer) checks internal and external links and a few other things. It uncovered some errors and non-existing links on the site, which I fixed in a second commit.

### CODE REVIEW

**Comment by jdavis** [comment]
Taking a look at this now, Florian.

**Comment by jdavis** [comment]
Wow. This is amazing. I want it for all of my sites that use Jekyll...

I think this looks great; let me know when it is [RDY] and it can be merged.

**Comment by jdavis** [comment]
I don't appear to have permission to turn on Travis for the repo. It looks like this is something an admin has to do (@justinmk).

**Comment by justinmk** [comment]
Done

**Comment by justinmk** [comment]
https://travis-ci.org/neovim/neovim.github.io

**Comment by jdavis** [comment]
I believe now you just need to add: `task :default => [:test]` below the import of the Rakefile.

**Comment by fwalch** [comment]
Hm. It doesn't pick that up locally.

```
 ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.2.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename.
```

As a side note, this build is amazingly fast, especially with caching.. we should check out if we can change some of the other repos's builds to not require sudo.

**Comment by fwalch** [comment]
Okay, got it.. the bundle was installed into `vendor` instead of a `.bundle` subfolder.. added `vendor/` to the `_config.yml`.

**Comment by jdavis** [comment]
Excellent.

**Pull request merged**
