### PR TITLE
Add pygeek website to sponsor override

### PR DESCRIPTION
**Pull request by pygeek**
I'd also like to include this image as my avatar on the sponsors page (https://pbs.twimg.com/profile_images/378800000436837670/4933f9be3fd1c43573c70808a5833278.png).

### CODE REVIEW

**Comment by justinmk** [comment]
Didn't realize that you didn't add the code for the avatar. I will take a look at it.

Thanks for sponsoring!

**Comment by justinmk** [comment]
I committed https://github.com/neovim/neovim.github.io/commit/f12fbd039bd59675428afe2c8e91585b4ddb71a2 but it's not working. @tarruda  any idea?

**Comment by tarruda** [comment]
thanks for the contribution, but as described in the rewards section of the [campaign](https://salt.bountysource.com/teams/neovim), only the "sponsor - small" tier gets an image in the list

> I committed f12fbd0 but it's not working. @tarruda any idea?

Yes, this [line](https://github.com/neovim/neovim.github.io/blob/master/sponsor-generator/lib/logo.js#L10) is responsible for setting the avatar, which uses the `imageUrl` field. The `frontImageUrl` field is only used to set a different logo for the front page. In any case, it won't work for @pygeek because only after $75 the custom image is used.

**Comment by pygeek** [comment]
Got it. Thanks. :-)

**Pull request merged**
