### PR TITLE
sponsors: add rizin.re

### PR DESCRIPTION
**Pull request by teto**
as @XVilka is entitled to. Sorry for delay and thanks for sponsoring !

### CODE REVIEW

**Comment by teto** [comment]
@XVilka is there a version of the logo with "rizin" written next to the "ananas" :)  ?

**Comment by thestr4ng3r** [comment]
rizin-text

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Thank you!

**Comment by teto** [comment]
this looks better thanks

**Review by XVilka — APPROVED** [review]

**Comment by thestr4ng3r** [comment]
The font is broken. Better use this version, it has the text baked as a vector object rather than needing the font:
rizin-text-baked

**Comment by teto** [comment]
what about ?

**Comment by XVilka** [comment]
Not a particular fan of this new font, but I think it's good enough. LGTM

**Comment by thestr4ng3r** [comment]
It's the same as on https://rizin.re/

**Comment by teto** [comment]
I merged that, if you want to update the logo, ping me on your PR

**Comment by justinmk** [comment]
should this also be on the main (index) page?

**Pull request merged**
