### PR TITLE
Refine website colors

### PR DESCRIPTION
**Pull request by rockerBOO**
This refines the current colors from more primary colors and shifts everything into the blue/green hue.

All colors to be AAA contrast accessibility. Except for the blue links on the dark background are AA. Blue is darker generally and this allowed us to keep the blue color more. 

Added underlines to all links. This helps with accessibility and scanning to find the links easily. 

Unset a lot of bootstrap values to set the font size in `<pre>`. Now defaults to the user's `monospace` font and their default browser font size for monospace. This allows users to use the font they like as well as support ligatures ;).

Changed the main button to be `Get Started` from `Install Now`. Add animated effect on hover/focus.

Adds animation (96ms) to link transitions.

Screenshot_2020-12-17 Home - Neovim(4)
Screenshot_2020-12-17 Home - Neovim(3)

[Screenshot_2020-12-17 Nvim documentation help(1)](https://user-images.githubusercontent.com/15027/102555903-b53e5d00-4095-11eb-8250-6beae7a79578.png)
[Screenshot_2020-12-17 Nvim documentation help](https://user-images.githubusercontent.com/15027/102555904-b53e5d00-4095-11eb-8363-c498a23003f6.png)

[Screenshot_2020-12-17 Home - Neovim(8)](https://user-images.githubusercontent.com/15027/102556049-ffbfd980-4095-11eb-8786-b8f812140e5d.png)
[Screenshot_2020-12-17 Home - Neovim(7)](https://user-images.githubusercontent.com/15027/102556050-00587000-4096-11eb-9965-a70f5bd281d7.png)
[Screenshot_2020-12-17 Home - Neovim(6)](https://user-images.githubusercontent.com/15027/102556051-00587000-4096-11eb-899f-e46a591d06d3.png)
[Screenshot_2020-12-17 Home - Neovim(5)](https://user-images.githubusercontent.com/15027/102556054-00587000-4096-11eb-8064-f7e15c74021f.png)

---

#### Original Screens 

[Screenshot_2020-12-08 Home - Neovim(6)](https://user-images.githubusercontent.com/15027/101533695-21b5af80-3964-11eb-91cd-86b39bfcbd38.png)

[Screenshot_2020-12-08 Home - Neovim(3)](https://user-images.githubusercontent.com/15027/101533708-25493680-3964-11eb-9383-d402349ce29f.png)

[Screenshot_2020-12-08 Nvim documentation help(3)](https://user-images.githubusercontent.com/15027/101534345-fd0e0780-3964-11eb-8df5-acf52977501b.png)

[Screenshot_2020-12-08 Nvim documentation lsp](https://user-images.githubusercontent.com/15027/101534356-00a18e80-3965-11eb-955a-867f39a0672d.png)

### CODE REVIEW

**Comment by rockerBOO** [comment]
I need to fix the header collapsing on mobile and then it should be good.

**Comment by rockerBOO** [comment]
I also need to redo the logo to work better on the dark version, but that's not a true blocker.

**Comment by teto** [comment]
I tried it locally, the header takes more (useless) space (dark version so maybe that's what you mentioned). 
I agree with underlining links, the web makes it hard to distinguish links now. I dont know for the menu though, it makes it uglier IMO.
In my case, the font got bigger but it's fine.

As for the colors, I find this dark green quite unusual, let's see what others will say.

**Comment by rockerBOO** [comment]
Yes the colors are a little contentious but I wanted an attempt to deviate from the common trend to make the dark version a gray base instead of adding a hint of color. Of course maybe it would be better to pick something more neutral.

I'll try to make a pass at tightening the header back up a little later. It was being artificially shrunk which was making it behave oddly so I can make it properly adjusted.

I can make  distinction for the top buttons to not have underline, but maybe it adds to the clarity?

**Comment by jamessan** [comment]
The green hue for the dark version I don't mind.  For the light version, I don't think it works well.

**Comment by teto** [comment]
just for intel about dark colors https://blog.karenying.com/posts/github-darkmode-sucks

**Comment by rockerBOO** [comment]
Ok going to give this another pass. 

For the dark: 
* The overall tones I think are generally accepted. The blue/green saturation may be too high. I can half the saturation and see if that feels any better.  
For the light: 
* The contrast is good but the seagreen colors are maybe too distinctive? Less green more gray? Or more blue? I will make a few screens showing some different options. 

@teto In terms of the dark mode, github made a few distinct decisions. 
The "error" state is the contrast of the color on lighter grey buttons (6.15 AA) vs a (7.0 AAA). So they can easily up the contrast there.
They chose a blue hue as their base instead of a de-saturated grey/white. This is the similar distinction I am going for with mine but maybe some refinement is necessary.

I am shooting for 10 contrast on everything, and we can have a [`prefers-contrast: forced` media query](https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/) to pump those numbers up to 15+.

**Comment by rockerBOO** [comment]
Screenshot_2020-12-13 Home - Neovim

Toned it back in half on the saturation for the light version. I think this looks a lot better.

**Comment by rockerBOO** [comment]
Lime green dark colors:
Screenshot_2020-12-13 Home - Neovim(1)

This hits 10 contrast, but no blue color.

```
      --fg-color: #c7d6d0;
      --bg-color: #202823;

      --accent-bg-color: #1c231e;
      --link-color:#81e771;
      --accent-color: #54a23d;

      --border-color: #353e39;
```

**Comment by rockerBOO** [comment]
Screenshot_2020-12-13 Home - Neovim(2)

```
      --fg-color: #c7d6d0;
      --bg-color: #202823;

      --accent-bg-color: #1c231e;
      --link-color: #b2e7aa;
      --accent-color: #85dbef;

      --border-color: #353e39;
```

**Comment by rockerBOO** [comment]
So in terms of colors, any blue on dark is tough to get the contrast high enough. Swapping to green allows more range in contrast, but it turns it more green.

**Comment by jamessan** [comment]
I like the new updates better, especially for the light theme.

Although it would be nice to tie in some blue, I see what you mean about the contrast not being as good.  I'm fine with just green.

**Comment by tjdevries** [comment]
I I like greens. Feels hacker mod meets nvim.

**Comment by rockerBOO** [comment]
This shows the colors using the same luminescence, where you can see blue is quite a bit darker. 

I am considering another attempt where the base dark is blue and we put a more neon green color as the accent/link colors.

**Comment by rockerBOO** [comment]
Screenshot_2020-12-14 Nvim documentation help
Screenshot_2020-12-14 Home - Neovim


```
--fg-color: #c7d6d0;
--bg-color: #0f191f;
--accent-bg-color: #0b151b;
--link-color: #81e771;
--accent-color: #7eea5e;
--border-color: #203f57;
```

**Comment by rockerBOO** [comment]
Screenshot_2020-12-14 Nvim documentation help(1)
Screenshot_2020-12-14 News - Neovim

Reduced the saturation on the green for the links.
- This should help to make the normal text not get so overpowered by the links. 
```
      --fg-color: #c7d6d0;
      --bg-color: #0f191f;
      --accent-bg-color: #0b151b;
      --link-color:#a8d0a2;
      --accent-color: #7eea5e;
      --border-color: #203f57;
```

**Comment by teto** [comment]
thanks for the effort, I very much like the last ones FWIW.

**Comment by rockerBOO** [comment]
I believe I have resolved all the issues in the main header. 

Screenshot_2020-12-17 Home - Neovim(4)
Screenshot_2020-12-17 Nvim documentation help(1)
Screenshot_2020-12-17 Nvim documentation help
Screenshot_2020-12-17 Home - Neovim(3)

Screenshot_2020-12-17 Home - Neovim(8)
Screenshot_2020-12-17 Home - Neovim(7)
Screenshot_2020-12-17 Home - Neovim(6)
Screenshot_2020-12-17 Home - Neovim(5)

**Comment by rockerBOO** [comment]
Seems my merging didn't make a clean branch. I can resolve this soon.

**Comment by rockerBOO** [comment]
I could not figure out how to fix my mistakes so I made a new branch and a new pull request.

**Comment by jamessan** [comment]
Merged via #208

**Pull request closed without merging**
